### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by reneklacan** [markhibberd/riak-haskell-client#10]
Hi, some examples that will show how the library can be used would be perfect!

Great work, by the way!

**Comment by tmcgilchrist** [comment]
@markhibberd putting my hand up to add some documentation for this. I was thinking of following the style of something like [MySQL Simple](https://hackage.haskell.org/package/mysql-simple-0.2.2.4/docs/src/Database-MySQL-Simple.html) so it gets displayed like [MySQL on hackage](https://hackage.haskell.org/package/mysql-simple-0.2.2.4/docs/Database-MySQL-Simple.html)

**Comment by markhibberd** [comment]
Yep, that sounds great. Thanks.

**Comment by markhibberd** [comment]
@tmcgilchrist There is also this style as well (which is pretty much the same) http://hackage.haskell.org/package/pipes-4.1.5/docs/Pipes-Tutorial.html but you can create a standalone empty module that is just the doc. No preference, just pointing out a twist on a similar style of thing.

**Comment by tmcgilchrist** [comment]
That style looks good too.

**Comment by tmcgilchrist** [comment]
Link to basic usage on the Basho website in this PR https://github.com/markhibberd/riak-haskell-client/pull/17

@reneklacan

**Comment by reneklacan** [comment]
Nice one! Thank you. I think we can close this issue. I am very pleased to see tutorial on official basho website.

**Comment by tmcgilchrist** [comment]
Let us know if you have issues with those docs. They should be enough to
get started with.

I'll be adding more detailed docs on the various modules in the coming
weeks, hopefully with some sample code.
