### ISSUE TITLE
Riak network error on deleted key

### ISSUE THREAD

**Issue by pparkkin** [markhibberd/riak-haskell-client#13]
I'm trying to run the code here: http://stackoverflow.com/a/24301559

Result is that the second get (for the deleted key) gives me the following:

    Riak network error (Network.Riak.Connection.Internal.exchangeMaybe GetRequest): recv: invalid argument (Bad file descriptor)

Version information.

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.6.3
    $ cabal list riak --installed
    * riak
        Synopsis: A Haskell client for the Riak decentralized data store
        Default available version: 0.7.2.1
        Installed versions: 0.7.2.1
        Homepage: http://github.com/markhibberd/riak-haskell-client
        License:  OtherLicense

**Comment by pparkkin** [comment]
Also getting same with version ghc 7.8.4.

**Comment by markhibberd** [comment]
@pparkkin  What version of Riak are you using?

**Comment by pparkkin** [comment]
Riak version is 2.0.2.

**Comment by markhibberd** [comment]
@pparkkin I haven't had any luck replicating, but I only have a 1.4 cluster up at the moment. Quite likely related to a change in the proto-buf defs between versions. I am probably not going to have a chance to get to it in the next week or so, but it will probably require a new version with regerated definitions.

**Comment by pparkkin** [comment]
Thanks for looking into it!

If I get the time this week, I'll take a look at the proto-buf defs, and see if I can figure out what's changed.

**Comment by tmcgilchrist** [comment]
@pparkkin i know this is an old issue, but is it still an issue for you?

**Comment by pparkkin** [comment]
@tmcgilchrist It is not.

I ended up not using Riak for what I was doing at the time. (Not because of this issue.)
