### ISSUE TITLE
Hackage version update

### ISSUE THREAD

**Issue by Jonplussed** [markhibberd/riak-haskell-client#27]
Hello! The team I'm with would like to use the Network.Riak.Cluster code, but no release on Hackage yet contains it. Would it be possible to issue a new release for Hackage?

Thanks!

**Comment by tmcgilchrist** [comment]
Sure I'll prep one and get it up on hackage in the next day or so.

**Comment by Jonplussed** [comment]
Thank you :smile_cat:

**Comment by tmcgilchrist** [comment]
Pushed a new version 0.9.1.0 up to hackage, please have a look and let us know if there are any issues.

https://hackage.haskell.org/package/riak

**Comment by Jonplussed** [comment]
Roger that; will do

**Comment by tmcgilchrist** [comment]
Assuming, due to the lack of wailing, that this version was ok. Closing

**Comment by Jonplussed** [comment]
@tmcgilchrist haha, yes, and thank you! Sorry, I completely forgot to respond further.
