### ISSUE TITLE
Request for new release with bucket types

### ISSUE THREAD

**Issue by sanketr** [markhibberd/riak-haskell-client#43]
Since `Riak 2+`, bucket types are standard (defaulting to "default" value if no bucket type is provided). Since they are missing outside `Network.Riak.CRDT` module in release `1.0.0.1`, it will be good to have another release where bucket types are available for all key-value requests (or wherever they make sense). 

Since all my data is modeled as CRDT for now, `1.0.0.1` works. But, as soon as I have non-CRDT data, the new release will help since I use bucket types every where (to separate out data into collections).

**Comment by tmcgilchrist** [comment]
Duly noted, I'll get onto this in the next day or so. Ping me again if it's not up on hackage this week.

**Comment by tmcgilchrist** [comment]
Actually the bucket types are already there, just uploaded 1.0.1.0 with them. Let me know how you go with that version.

**Comment by sanketr** [comment]
Cool, yep, bucket types are there in main branch - hence, the request for release :) Could you upload it to stackage as well? I am building my code against stackage.

**Comment by tmcgilchrist** [comment]
I believe it should be picked up in Stackage nightly build at some point. I don't use stackage much so I'm not 100% sure when.
Which version of the stackage index are you using?

You know you could always override the version in stack using this in your stack.yaml
```haskell
extra-deps:
- riak-1.0.1.0
```

**Comment by sanketr** [comment]
I have setting like below in my stack.yaml for `1.0.0.1`- I am using git hash for release `1.0.0.1`.

packages:
#  - location:
#      git: https://github.com/markhibberd/riak-haskell-client.git
#      commit: 010653c0e4ba6a1eb224b9fa259d84ebf6275fe9
- '.'
extra-deps:
- riak-1.0.0.1
- riak-protobuf-0.21.0.0

**Comment by sanketr** [comment]
@tmcgilchrist, are you sure hackage has the new version 1.0.1.0? I just browsed the source code on hackage, and saw the old version 1.0.0.1. It seems to me that you need to do a new release on github - I am not very familiar with how hackage works - so, my apologies in case I am wrong. I am still waiting for stackage nightly to update with new version 1.0.1.0 before I can download it.

**Comment by tmcgilchrist** [comment]
Yeah I messed up the release apologies, the 1.0.1.1 version looks like it has the BucketType available in most placed. @sanketr

**Comment by qrilka** [comment]
@tmcgilchrist it's a quite confusing that API gets broken in "subpatch" version update 1.0.1.0 → 1.0.1.1
I mean BucketType appearing as an extra argument

**Comment by k-bx** [comment]
Yeah, that's a really not a good way to go. I suggest having 1.0.1.2 undoing API-breakage, and doing a major version bump.
