### ISSUE TITLE
Improve riak configuration for CI.

### ISSUE THREAD

**Issue by markhibberd** [markhibberd/riak-haskell-client#8]
Currently it is a default 1.4.8 install with corresponding default configuration. Should at least have:
 - allow_mult = true
 - lww = false

**Comment by tmcgilchrist** [comment]
We're getting multi ghc and multi riak support in the Riak 2.* pr, is this still worthwhile?

Maybe we want to backport multi riak support into the 0.9 branch to test against the last 2 stable versions of riak 1.* .
