### ISSUE TITLE
Monad Transformer compatible versions of `modify` and `modify_`

### ISSUE THREAD

**Issue by Davorak** [markhibberd/riak-haskell-client#9]
With `put` and `get` it is simple to just use `liftIO` to lift them into any monad transformer, however this is not possible with the update function passed into `modify` and `modify_`. 

One example use is to test staggered `modify` like sequences as I described in [pull #7](https://github.com/markhibberd/riak-haskell-client/pull/7#issuecomment-42816877).

Are there any downsides to adding these monad transformer compatible versions? I currently do not see why they could not replace the current versions.

Here is is sketch of a program that might test staggered `modify`s:

    import Pipes                                                                 
    import qualified Pipes.Prelude as P                                          
                                                                                 
    import Network.Riak.Types                                                    
    import Network.Riak.JSON.Resolvable                                          
                                                                                 
    import qualified Data.ByteString.Lazy as Lazy                                
                                                                                 
    import Data.Aeson                                                            
                                                                                 
    {-                                                                           
    modifyM_ :: (MonadIO m, Resolvable a) => Get a -> Put a                      
            -> Connection -> Bucket -> Key -> R -> W -> DW -> (Maybe a -> m a)   
            -> m a                                                               
    modifyM_ doGet doPut conn bucket key r w dw act = do                         
      a0 <- liftIO $ get doGet conn bucket key r                                 
      a <- act (fst <$> a0)                                                      
      liftIO $ fst <$> put doPut conn bucket key (snd <$> a0) a w dw             
    -}                                                                           
                                                                                 
    stagger1                                                                     
      :: (MonadIO m, ToJSON a,                                                   
          FromJSON a, Resolvable a) =>                                           
         Connection                                                              
         -> Bucket -> Key -> Producer () m a                                     
    stagger1 conn bucket key = loop                                              
      where                                                                      
        loop = do                                                                
            r <- modifyM_ conn bucket key Default Default Default $ \ma -> do    
                yield ()                                                         
                updatefn undefined ma                                            
            yield ()                                                             
            return r                                                             
        updatefn value ma = undefined                                            
                                                                                 
    stagger2                                                                     
      :: (MonadIO m, ToJSON a, FromJSON a, Resolvable a) =>                      
         Connection                                                              
         -> Bucket -> Key -> Consumer () m a                                     
    stagger2 conn bucket key = loop                                              
      where                                                                      
        loop = do                                                                
            () <- await                                                          
            modifyM_ conn bucket key Default Default Default $ \ma -> do         
                () <- await                                                      
                updatefn undefined ma                                            
        updatefn value ma = undefined                                            
                                                                                 
    {-                                                                           
    > :t stagger1 conn1 "test" "test" >-> stagger2 conn2 "test" "test"           
    stagger1 conn1 "test" "test" >-> stagger2 conn2 "test" "test"                
      :: (MonadIO m, ToJSON r, FromJSON r, Resolvable r) =>                      
         Proxy a' a c' c m r                                                     
    -}

**Comment by tmcgilchrist** [comment]
Pulled the code from @Davorak into the linked PR. 
Let me know @markhibberd if it's ok.

**Comment by tmcgilchrist** [comment]
Merged https://github.com/markhibberd/riak-haskell-client/pull/19
